server:
  port: 8090
spring:
  application:
    name: client-service
  devtools:
    add-properties: false
  profiles:
    include: null
  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.application.name}
